name: Deploy

on:
  push:
    branches:
      - main

env:
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  REGION: asia-northeast1
  ENV: production
  JOB_NAME: node-gcloud-release-crawler

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    if: github.ref_name == 'main'
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          REPOSITORY=${{ env.REGION }}-docker.pkg.dev/${{ env.GOOGLE_PROJECT_ID }}/node-gcloud-release-crawler
          IMAGE=${REPOSITORY}/node-gcloud-release-crawler:latest
          docker pull ${IMAGE} || true
          docker build --cache-from ${IMAGE} -t ${IMAGE} .
          docker push ${IMAGE}

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy ${{ env.JOB_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.GOOGLE_PROJECT_ID }}/node-gcloud-release-crawler/node-gcloud-release-crawler:latest \
            --region ${{ env.REGION }} \
            --task-timeout 600 \
            --max-retries 3 \
            --service-account ${{ secrets.GOOGLE_SA_EMAIL }}
